/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthRegisterPatientRouteImport } from './routes/auth.register-patient'
import { Route as AuthRegisterDoctorRouteImport } from './routes/auth.register-doctor'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppEvolutionRouteImport } from './routes/app.evolution'
import { Route as AppClinicProfileRouteImport } from './routes/app.clinic-profile'
import { Route as AppCameraRouteImport } from './routes/app.camera'
import { Route as AdminWikiRouteImport } from './routes/admin.wiki'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomizeRouteImport } from './routes/admin.customize'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AppWikiSearchRouteImport } from './routes/app.wiki.search'
import { Route as AppWikiSlugRouteImport } from './routes/app.wiki.$slug'
import { Route as AppContentFeedRouteImport } from './routes/app.content.feed'
import { Route as AppContentSlugRouteImport } from './routes/app.content.$slug'
import { Route as AdminWikiNewRouteImport } from './routes/admin.wiki.new'
import { Route as AdminPatientsIdRouteImport } from './routes/admin.patients.$id'
import { Route as AdminContentNewRouteImport } from './routes/admin.content.new'
import { Route as AdminContentListRouteImport } from './routes/admin.content.list'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterPatientRoute = AuthRegisterPatientRouteImport.update({
  id: '/auth/register-patient',
  path: '/auth/register-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterDoctorRoute = AuthRegisterDoctorRouteImport.update({
  id: '/auth/register-doctor',
  path: '/auth/register-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolutionRoute = AppEvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicProfileRoute = AppClinicProfileRouteImport.update({
  id: '/clinic-profile',
  path: '/clinic-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppCameraRoute = AppCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AppRoute,
} as any)
const AdminWikiRoute = AdminWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomizeRoute = AdminCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AppWikiSearchRoute = AppWikiSearchRouteImport.update({
  id: '/wiki/search',
  path: '/wiki/search',
  getParentRoute: () => AppRoute,
} as any)
const AppWikiSlugRoute = AppWikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppContentFeedRoute = AppContentFeedRouteImport.update({
  id: '/content/feed',
  path: '/content/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppContentSlugRoute = AppContentSlugRouteImport.update({
  id: '/content/$slug',
  path: '/content/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AdminWikiNewRoute = AdminWikiNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminWikiRoute,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminContentNewRoute = AdminContentNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminContentRoute,
} as any)
const AdminContentListRoute = AdminContentListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => AdminContentRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/customize': typeof AdminCustomizeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/wiki': typeof AdminWikiRouteWithChildren
  '/app/camera': typeof AppCameraRoute
  '/app/clinic-profile': typeof AppClinicProfileRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/home': typeof AppHomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-doctor': typeof AuthRegisterDoctorRoute
  '/auth/register-patient': typeof AuthRegisterPatientRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/content/list': typeof AdminContentListRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/wiki/new': typeof AdminWikiNewRoute
  '/app/content/$slug': typeof AppContentSlugRoute
  '/app/content/feed': typeof AppContentFeedRoute
  '/app/wiki/$slug': typeof AppWikiSlugRoute
  '/app/wiki/search': typeof AppWikiSearchRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/customize': typeof AdminCustomizeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/wiki': typeof AdminWikiRouteWithChildren
  '/app/camera': typeof AppCameraRoute
  '/app/clinic-profile': typeof AppClinicProfileRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/home': typeof AppHomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-doctor': typeof AuthRegisterDoctorRoute
  '/auth/register-patient': typeof AuthRegisterPatientRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/content/list': typeof AdminContentListRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/wiki/new': typeof AdminWikiNewRoute
  '/app/content/$slug': typeof AppContentSlugRoute
  '/app/content/feed': typeof AppContentFeedRoute
  '/app/wiki/$slug': typeof AppWikiSlugRoute
  '/app/wiki/search': typeof AppWikiSearchRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/content': typeof AdminContentRouteWithChildren
  '/admin/customize': typeof AdminCustomizeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/wiki': typeof AdminWikiRouteWithChildren
  '/app/camera': typeof AppCameraRoute
  '/app/clinic-profile': typeof AppClinicProfileRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/home': typeof AppHomeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-doctor': typeof AuthRegisterDoctorRoute
  '/auth/register-patient': typeof AuthRegisterPatientRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/content/list': typeof AdminContentListRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/wiki/new': typeof AdminWikiNewRoute
  '/app/content/$slug': typeof AppContentSlugRoute
  '/app/content/feed': typeof AppContentFeedRoute
  '/app/wiki/$slug': typeof AppWikiSlugRoute
  '/app/wiki/search': typeof AppWikiSearchRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/billing'
    | '/admin/content'
    | '/admin/customize'
    | '/admin/dashboard'
    | '/admin/patients'
    | '/admin/profile'
    | '/admin/wiki'
    | '/app/camera'
    | '/app/clinic-profile'
    | '/app/evolution'
    | '/app/home'
    | '/auth/login'
    | '/auth/register-doctor'
    | '/auth/register-patient'
    | '/checkout/return'
    | '/admin/content/list'
    | '/admin/content/new'
    | '/admin/patients/$id'
    | '/admin/wiki/new'
    | '/app/content/$slug'
    | '/app/content/feed'
    | '/app/wiki/$slug'
    | '/app/wiki/search'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/billing'
    | '/admin/content'
    | '/admin/customize'
    | '/admin/dashboard'
    | '/admin/patients'
    | '/admin/profile'
    | '/admin/wiki'
    | '/app/camera'
    | '/app/clinic-profile'
    | '/app/evolution'
    | '/app/home'
    | '/auth/login'
    | '/auth/register-doctor'
    | '/auth/register-patient'
    | '/checkout/return'
    | '/admin/content/list'
    | '/admin/content/new'
    | '/admin/patients/$id'
    | '/admin/wiki/new'
    | '/app/content/$slug'
    | '/app/content/feed'
    | '/app/wiki/$slug'
    | '/app/wiki/search'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/billing'
    | '/admin/content'
    | '/admin/customize'
    | '/admin/dashboard'
    | '/admin/patients'
    | '/admin/profile'
    | '/admin/wiki'
    | '/app/camera'
    | '/app/clinic-profile'
    | '/app/evolution'
    | '/app/home'
    | '/auth/login'
    | '/auth/register-doctor'
    | '/auth/register-patient'
    | '/checkout/return'
    | '/admin/content/list'
    | '/admin/content/new'
    | '/admin/patients/$id'
    | '/admin/wiki/new'
    | '/app/content/$slug'
    | '/app/content/feed'
    | '/app/wiki/$slug'
    | '/app/wiki/search'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterDoctorRoute: typeof AuthRegisterDoctorRoute
  AuthRegisterPatientRoute: typeof AuthRegisterPatientRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register-patient': {
      id: '/auth/register-patient'
      path: '/auth/register-patient'
      fullPath: '/auth/register-patient'
      preLoaderRoute: typeof AuthRegisterPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register-doctor': {
      id: '/auth/register-doctor'
      path: '/auth/register-doctor'
      fullPath: '/auth/register-doctor'
      preLoaderRoute: typeof AuthRegisterDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evolution': {
      id: '/app/evolution'
      path: '/evolution'
      fullPath: '/app/evolution'
      preLoaderRoute: typeof AppEvolutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinic-profile': {
      id: '/app/clinic-profile'
      path: '/clinic-profile'
      fullPath: '/app/clinic-profile'
      preLoaderRoute: typeof AppClinicProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/camera': {
      id: '/app/camera'
      path: '/camera'
      fullPath: '/app/camera'
      preLoaderRoute: typeof AppCameraRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/wiki': {
      id: '/admin/wiki'
      path: '/wiki'
      fullPath: '/admin/wiki'
      preLoaderRoute: typeof AdminWikiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customize': {
      id: '/admin/customize'
      path: '/customize'
      fullPath: '/admin/customize'
      preLoaderRoute: typeof AdminCustomizeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/wiki/search': {
      id: '/app/wiki/search'
      path: '/wiki/search'
      fullPath: '/app/wiki/search'
      preLoaderRoute: typeof AppWikiSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wiki/$slug': {
      id: '/app/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/app/wiki/$slug'
      preLoaderRoute: typeof AppWikiSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content/feed': {
      id: '/app/content/feed'
      path: '/content/feed'
      fullPath: '/app/content/feed'
      preLoaderRoute: typeof AppContentFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content/$slug': {
      id: '/app/content/$slug'
      path: '/content/$slug'
      fullPath: '/app/content/$slug'
      preLoaderRoute: typeof AppContentSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/wiki/new': {
      id: '/admin/wiki/new'
      path: '/new'
      fullPath: '/admin/wiki/new'
      preLoaderRoute: typeof AdminWikiNewRouteImport
      parentRoute: typeof AdminWikiRoute
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/content/new': {
      id: '/admin/content/new'
      path: '/new'
      fullPath: '/admin/content/new'
      preLoaderRoute: typeof AdminContentNewRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/admin/content/list': {
      id: '/admin/content/list'
      path: '/list'
      fullPath: '/admin/content/list'
      preLoaderRoute: typeof AdminContentListRouteImport
      parentRoute: typeof AdminContentRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminContentRouteChildren {
  AdminContentListRoute: typeof AdminContentListRoute
  AdminContentNewRoute: typeof AdminContentNewRoute
}

const AdminContentRouteChildren: AdminContentRouteChildren = {
  AdminContentListRoute: AdminContentListRoute,
  AdminContentNewRoute: AdminContentNewRoute,
}

const AdminContentRouteWithChildren = AdminContentRoute._addFileChildren(
  AdminContentRouteChildren,
)

interface AdminPatientsRouteChildren {
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
}

const AdminPatientsRouteChildren: AdminPatientsRouteChildren = {
  AdminPatientsIdRoute: AdminPatientsIdRoute,
}

const AdminPatientsRouteWithChildren = AdminPatientsRoute._addFileChildren(
  AdminPatientsRouteChildren,
)

interface AdminWikiRouteChildren {
  AdminWikiNewRoute: typeof AdminWikiNewRoute
}

const AdminWikiRouteChildren: AdminWikiRouteChildren = {
  AdminWikiNewRoute: AdminWikiNewRoute,
}

const AdminWikiRouteWithChildren = AdminWikiRoute._addFileChildren(
  AdminWikiRouteChildren,
)

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminContentRoute: typeof AdminContentRouteWithChildren
  AdminCustomizeRoute: typeof AdminCustomizeRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPatientsRoute: typeof AdminPatientsRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminWikiRoute: typeof AdminWikiRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminContentRoute: AdminContentRouteWithChildren,
  AdminCustomizeRoute: AdminCustomizeRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPatientsRoute: AdminPatientsRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminWikiRoute: AdminWikiRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppCameraRoute: typeof AppCameraRoute
  AppClinicProfileRoute: typeof AppClinicProfileRoute
  AppEvolutionRoute: typeof AppEvolutionRoute
  AppHomeRoute: typeof AppHomeRoute
  AppContentSlugRoute: typeof AppContentSlugRoute
  AppContentFeedRoute: typeof AppContentFeedRoute
  AppWikiSlugRoute: typeof AppWikiSlugRoute
  AppWikiSearchRoute: typeof AppWikiSearchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCameraRoute: AppCameraRoute,
  AppClinicProfileRoute: AppClinicProfileRoute,
  AppEvolutionRoute: AppEvolutionRoute,
  AppHomeRoute: AppHomeRoute,
  AppContentSlugRoute: AppContentSlugRoute,
  AppContentFeedRoute: AppContentFeedRoute,
  AppWikiSlugRoute: AppWikiSlugRoute,
  AppWikiSearchRoute: AppWikiSearchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterDoctorRoute: AuthRegisterDoctorRoute,
  AuthRegisterPatientRoute: AuthRegisterPatientRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
