/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthRegisterPatientRouteImport } from './routes/auth.register-patient'
import { Route as AuthRegisterDoctorRouteImport } from './routes/auth.register-doctor'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppUvRouteImport } from './routes/app.uv'
import { Route as AppSymptomResultsRouteImport } from './routes/app.symptom-results'
import { Route as AppSymptomCheckerRouteImport } from './routes/app.symptom-checker'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSplashRouteImport } from './routes/app.splash'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppLesionResultsRouteImport } from './routes/app.lesion-results'
import { Route as AppLesionCameraRouteImport } from './routes/app.lesion-camera'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppEvolutionRouteImport } from './routes/app.evolution'
import { Route as AppContentRouteImport } from './routes/app.content'
import { Route as AppClinicProfileRouteImport } from './routes/app.clinic-profile'
import { Route as AppClinicCodeRouteImport } from './routes/app.clinic-code'
import { Route as AppCameraRouteImport } from './routes/app.camera'
import { Route as AdminWikiRouteImport } from './routes/admin.wiki'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomizeRouteImport } from './routes/admin.customize'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminContentIndexRouteImport } from './routes/admin.content.index'
import { Route as AppWikiSearchRouteImport } from './routes/app.wiki.search'
import { Route as AppWikiSlugRouteImport } from './routes/app.wiki.$slug'
import { Route as AppScheduleConfirmedRouteImport } from './routes/app.schedule.confirmed'
import { Route as AppScheduleDoctorIdRouteImport } from './routes/app.schedule.$doctorId'
import { Route as AppLibraryResultsRouteImport } from './routes/app.library.results'
import { Route as AppContentFeedRouteImport } from './routes/app.content.feed'
import { Route as AppContentSlugRouteImport } from './routes/app.content.$slug'
import { Route as AppConditionSlugRouteImport } from './routes/app.condition.$slug'
import { Route as AdminWikiNewRouteImport } from './routes/admin.wiki.new'
import { Route as AdminPatientsIdRouteImport } from './routes/admin.patients.$id'
import { Route as AdminContentVideoEditorRouteImport } from './routes/admin.content.video-editor'
import { Route as AdminContentNewRouteImport } from './routes/admin.content.new'
import { Route as AdminContentListRouteImport } from './routes/admin.content.list'
import { Route as AppLibraryConditionsIdRouteImport } from './routes/app.library.conditions.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterPatientRoute = AuthRegisterPatientRouteImport.update({
  id: '/auth/register-patient',
  path: '/auth/register-patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterDoctorRoute = AuthRegisterDoctorRouteImport.update({
  id: '/auth/register-doctor',
  path: '/auth/register-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUvRoute = AppUvRouteImport.update({
  id: '/uv',
  path: '/uv',
  getParentRoute: () => AppRoute,
} as any)
const AppSymptomResultsRoute = AppSymptomResultsRouteImport.update({
  id: '/symptom-results',
  path: '/symptom-results',
  getParentRoute: () => AppRoute,
} as any)
const AppSymptomCheckerRoute = AppSymptomCheckerRouteImport.update({
  id: '/symptom-checker',
  path: '/symptom-checker',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSplashRoute = AppSplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppLesionResultsRoute = AppLesionResultsRouteImport.update({
  id: '/lesion-results',
  path: '/lesion-results',
  getParentRoute: () => AppRoute,
} as any)
const AppLesionCameraRoute = AppLesionCameraRouteImport.update({
  id: '/lesion-camera',
  path: '/lesion-camera',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppEvolutionRoute = AppEvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => AppRoute,
} as any)
const AppContentRoute = AppContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicProfileRoute = AppClinicProfileRouteImport.update({
  id: '/clinic-profile',
  path: '/clinic-profile',
  getParentRoute: () => AppRoute,
} as any)
const AppClinicCodeRoute = AppClinicCodeRouteImport.update({
  id: '/clinic-code',
  path: '/clinic-code',
  getParentRoute: () => AppRoute,
} as any)
const AppCameraRoute = AppCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AppRoute,
} as any)
const AdminWikiRoute = AdminWikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomizeRoute = AdminCustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentIndexRoute = AdminContentIndexRouteImport.update({
  id: '/content/',
  path: '/content/',
  getParentRoute: () => AdminRoute,
} as any)
const AppWikiSearchRoute = AppWikiSearchRouteImport.update({
  id: '/wiki/search',
  path: '/wiki/search',
  getParentRoute: () => AppRoute,
} as any)
const AppWikiSlugRoute = AppWikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleConfirmedRoute = AppScheduleConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => AppScheduleRoute,
} as any)
const AppScheduleDoctorIdRoute = AppScheduleDoctorIdRouteImport.update({
  id: '/$doctorId',
  path: '/$doctorId',
  getParentRoute: () => AppScheduleRoute,
} as any)
const AppLibraryResultsRoute = AppLibraryResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppLibraryRoute,
} as any)
const AppContentFeedRoute = AppContentFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppContentRoute,
} as any)
const AppContentSlugRoute = AppContentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppContentRoute,
} as any)
const AppConditionSlugRoute = AppConditionSlugRouteImport.update({
  id: '/condition/$slug',
  path: '/condition/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AdminWikiNewRoute = AdminWikiNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminWikiRoute,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminContentVideoEditorRoute = AdminContentVideoEditorRouteImport.update({
  id: '/content/video-editor',
  path: '/content/video-editor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentNewRoute = AdminContentNewRouteImport.update({
  id: '/content/new',
  path: '/content/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentListRoute = AdminContentListRouteImport.update({
  id: '/content/list',
  path: '/content/list',
  getParentRoute: () => AdminRoute,
} as any)
const AppLibraryConditionsIdRoute = AppLibraryConditionsIdRouteImport.update({
  id: '/conditions/$id',
  path: '/conditions/$id',
  getParentRoute: () => AppLibraryRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/customize': typeof AdminCustomizeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/wiki': typeof AdminWikiRouteWithChildren
  '/app/camera': typeof AppCameraRoute
  '/app/clinic-code': typeof AppClinicCodeRoute
  '/app/clinic-profile': typeof AppClinicProfileRoute
  '/app/content': typeof AppContentRouteWithChildren
  '/app/evolution': typeof AppEvolutionRoute
  '/app/history': typeof AppHistoryRoute
  '/app/home': typeof AppHomeRoute
  '/app/lesion-camera': typeof AppLesionCameraRoute
  '/app/lesion-results': typeof AppLesionResultsRoute
  '/app/library': typeof AppLibraryRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/schedule': typeof AppScheduleRouteWithChildren
  '/app/splash': typeof AppSplashRoute
  '/app/support': typeof AppSupportRoute
  '/app/symptom-checker': typeof AppSymptomCheckerRoute
  '/app/symptom-results': typeof AppSymptomResultsRoute
  '/app/uv': typeof AppUvRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-doctor': typeof AuthRegisterDoctorRoute
  '/auth/register-patient': typeof AuthRegisterPatientRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/content/list': typeof AdminContentListRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/admin/content/video-editor': typeof AdminContentVideoEditorRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/wiki/new': typeof AdminWikiNewRoute
  '/app/condition/$slug': typeof AppConditionSlugRoute
  '/app/content/$slug': typeof AppContentSlugRoute
  '/app/content/feed': typeof AppContentFeedRoute
  '/app/library/results': typeof AppLibraryResultsRoute
  '/app/schedule/$doctorId': typeof AppScheduleDoctorIdRoute
  '/app/schedule/confirmed': typeof AppScheduleConfirmedRoute
  '/app/wiki/$slug': typeof AppWikiSlugRoute
  '/app/wiki/search': typeof AppWikiSearchRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/library/conditions/$id': typeof AppLibraryConditionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/customize': typeof AdminCustomizeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/wiki': typeof AdminWikiRouteWithChildren
  '/app/camera': typeof AppCameraRoute
  '/app/clinic-code': typeof AppClinicCodeRoute
  '/app/clinic-profile': typeof AppClinicProfileRoute
  '/app/content': typeof AppContentRouteWithChildren
  '/app/evolution': typeof AppEvolutionRoute
  '/app/history': typeof AppHistoryRoute
  '/app/home': typeof AppHomeRoute
  '/app/lesion-camera': typeof AppLesionCameraRoute
  '/app/lesion-results': typeof AppLesionResultsRoute
  '/app/library': typeof AppLibraryRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/schedule': typeof AppScheduleRouteWithChildren
  '/app/splash': typeof AppSplashRoute
  '/app/support': typeof AppSupportRoute
  '/app/symptom-checker': typeof AppSymptomCheckerRoute
  '/app/symptom-results': typeof AppSymptomResultsRoute
  '/app/uv': typeof AppUvRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-doctor': typeof AuthRegisterDoctorRoute
  '/auth/register-patient': typeof AuthRegisterPatientRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/content/list': typeof AdminContentListRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/admin/content/video-editor': typeof AdminContentVideoEditorRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/wiki/new': typeof AdminWikiNewRoute
  '/app/condition/$slug': typeof AppConditionSlugRoute
  '/app/content/$slug': typeof AppContentSlugRoute
  '/app/content/feed': typeof AppContentFeedRoute
  '/app/library/results': typeof AppLibraryResultsRoute
  '/app/schedule/$doctorId': typeof AppScheduleDoctorIdRoute
  '/app/schedule/confirmed': typeof AppScheduleConfirmedRoute
  '/app/wiki/$slug': typeof AppWikiSlugRoute
  '/app/wiki/search': typeof AppWikiSearchRoute
  '/admin/content': typeof AdminContentIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/library/conditions/$id': typeof AppLibraryConditionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/customize': typeof AdminCustomizeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/profile': typeof AdminProfileRoute
  '/admin/wiki': typeof AdminWikiRouteWithChildren
  '/app/camera': typeof AppCameraRoute
  '/app/clinic-code': typeof AppClinicCodeRoute
  '/app/clinic-profile': typeof AppClinicProfileRoute
  '/app/content': typeof AppContentRouteWithChildren
  '/app/evolution': typeof AppEvolutionRoute
  '/app/history': typeof AppHistoryRoute
  '/app/home': typeof AppHomeRoute
  '/app/lesion-camera': typeof AppLesionCameraRoute
  '/app/lesion-results': typeof AppLesionResultsRoute
  '/app/library': typeof AppLibraryRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/schedule': typeof AppScheduleRouteWithChildren
  '/app/splash': typeof AppSplashRoute
  '/app/support': typeof AppSupportRoute
  '/app/symptom-checker': typeof AppSymptomCheckerRoute
  '/app/symptom-results': typeof AppSymptomResultsRoute
  '/app/uv': typeof AppUvRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register-doctor': typeof AuthRegisterDoctorRoute
  '/auth/register-patient': typeof AuthRegisterPatientRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/admin/content/list': typeof AdminContentListRoute
  '/admin/content/new': typeof AdminContentNewRoute
  '/admin/content/video-editor': typeof AdminContentVideoEditorRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/wiki/new': typeof AdminWikiNewRoute
  '/app/condition/$slug': typeof AppConditionSlugRoute
  '/app/content/$slug': typeof AppContentSlugRoute
  '/app/content/feed': typeof AppContentFeedRoute
  '/app/library/results': typeof AppLibraryResultsRoute
  '/app/schedule/$doctorId': typeof AppScheduleDoctorIdRoute
  '/app/schedule/confirmed': typeof AppScheduleConfirmedRoute
  '/app/wiki/$slug': typeof AppWikiSlugRoute
  '/app/wiki/search': typeof AppWikiSearchRoute
  '/admin/content/': typeof AdminContentIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/app/library/conditions/$id': typeof AppLibraryConditionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/billing'
    | '/admin/customize'
    | '/admin/dashboard'
    | '/admin/patients'
    | '/admin/profile'
    | '/admin/wiki'
    | '/app/camera'
    | '/app/clinic-code'
    | '/app/clinic-profile'
    | '/app/content'
    | '/app/evolution'
    | '/app/history'
    | '/app/home'
    | '/app/lesion-camera'
    | '/app/lesion-results'
    | '/app/library'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/schedule'
    | '/app/splash'
    | '/app/support'
    | '/app/symptom-checker'
    | '/app/symptom-results'
    | '/app/uv'
    | '/auth/login'
    | '/auth/register-doctor'
    | '/auth/register-patient'
    | '/checkout/return'
    | '/admin/content/list'
    | '/admin/content/new'
    | '/admin/content/video-editor'
    | '/admin/patients/$id'
    | '/admin/wiki/new'
    | '/app/condition/$slug'
    | '/app/content/$slug'
    | '/app/content/feed'
    | '/app/library/results'
    | '/app/schedule/$doctorId'
    | '/app/schedule/confirmed'
    | '/app/wiki/$slug'
    | '/app/wiki/search'
    | '/admin/content/'
    | '/api/public/payments/webhook'
    | '/app/library/conditions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/billing'
    | '/admin/customize'
    | '/admin/dashboard'
    | '/admin/patients'
    | '/admin/profile'
    | '/admin/wiki'
    | '/app/camera'
    | '/app/clinic-code'
    | '/app/clinic-profile'
    | '/app/content'
    | '/app/evolution'
    | '/app/history'
    | '/app/home'
    | '/app/lesion-camera'
    | '/app/lesion-results'
    | '/app/library'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/schedule'
    | '/app/splash'
    | '/app/support'
    | '/app/symptom-checker'
    | '/app/symptom-results'
    | '/app/uv'
    | '/auth/login'
    | '/auth/register-doctor'
    | '/auth/register-patient'
    | '/checkout/return'
    | '/admin/content/list'
    | '/admin/content/new'
    | '/admin/content/video-editor'
    | '/admin/patients/$id'
    | '/admin/wiki/new'
    | '/app/condition/$slug'
    | '/app/content/$slug'
    | '/app/content/feed'
    | '/app/library/results'
    | '/app/schedule/$doctorId'
    | '/app/schedule/confirmed'
    | '/app/wiki/$slug'
    | '/app/wiki/search'
    | '/admin/content'
    | '/api/public/payments/webhook'
    | '/app/library/conditions/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/onboarding'
    | '/admin/billing'
    | '/admin/customize'
    | '/admin/dashboard'
    | '/admin/patients'
    | '/admin/profile'
    | '/admin/wiki'
    | '/app/camera'
    | '/app/clinic-code'
    | '/app/clinic-profile'
    | '/app/content'
    | '/app/evolution'
    | '/app/history'
    | '/app/home'
    | '/app/lesion-camera'
    | '/app/lesion-results'
    | '/app/library'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/schedule'
    | '/app/splash'
    | '/app/support'
    | '/app/symptom-checker'
    | '/app/symptom-results'
    | '/app/uv'
    | '/auth/login'
    | '/auth/register-doctor'
    | '/auth/register-patient'
    | '/checkout/return'
    | '/admin/content/list'
    | '/admin/content/new'
    | '/admin/content/video-editor'
    | '/admin/patients/$id'
    | '/admin/wiki/new'
    | '/app/condition/$slug'
    | '/app/content/$slug'
    | '/app/content/feed'
    | '/app/library/results'
    | '/app/schedule/$doctorId'
    | '/app/schedule/confirmed'
    | '/app/wiki/$slug'
    | '/app/wiki/search'
    | '/admin/content/'
    | '/api/public/payments/webhook'
    | '/app/library/conditions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterDoctorRoute: typeof AuthRegisterDoctorRoute
  AuthRegisterPatientRoute: typeof AuthRegisterPatientRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register-patient': {
      id: '/auth/register-patient'
      path: '/auth/register-patient'
      fullPath: '/auth/register-patient'
      preLoaderRoute: typeof AuthRegisterPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register-doctor': {
      id: '/auth/register-doctor'
      path: '/auth/register-doctor'
      fullPath: '/auth/register-doctor'
      preLoaderRoute: typeof AuthRegisterDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/uv': {
      id: '/app/uv'
      path: '/uv'
      fullPath: '/app/uv'
      preLoaderRoute: typeof AppUvRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/symptom-results': {
      id: '/app/symptom-results'
      path: '/symptom-results'
      fullPath: '/app/symptom-results'
      preLoaderRoute: typeof AppSymptomResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/symptom-checker': {
      id: '/app/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/app/symptom-checker'
      preLoaderRoute: typeof AppSymptomCheckerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/splash': {
      id: '/app/splash'
      path: '/splash'
      fullPath: '/app/splash'
      preLoaderRoute: typeof AppSplashRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lesion-results': {
      id: '/app/lesion-results'
      path: '/lesion-results'
      fullPath: '/app/lesion-results'
      preLoaderRoute: typeof AppLesionResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lesion-camera': {
      id: '/app/lesion-camera'
      path: '/lesion-camera'
      fullPath: '/app/lesion-camera'
      preLoaderRoute: typeof AppLesionCameraRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/evolution': {
      id: '/app/evolution'
      path: '/evolution'
      fullPath: '/app/evolution'
      preLoaderRoute: typeof AppEvolutionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/content': {
      id: '/app/content'
      path: '/content'
      fullPath: '/app/content'
      preLoaderRoute: typeof AppContentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinic-profile': {
      id: '/app/clinic-profile'
      path: '/clinic-profile'
      fullPath: '/app/clinic-profile'
      preLoaderRoute: typeof AppClinicProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clinic-code': {
      id: '/app/clinic-code'
      path: '/clinic-code'
      fullPath: '/app/clinic-code'
      preLoaderRoute: typeof AppClinicCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/camera': {
      id: '/app/camera'
      path: '/camera'
      fullPath: '/app/camera'
      preLoaderRoute: typeof AppCameraRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/wiki': {
      id: '/admin/wiki'
      path: '/wiki'
      fullPath: '/admin/wiki'
      preLoaderRoute: typeof AdminWikiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customize': {
      id: '/admin/customize'
      path: '/customize'
      fullPath: '/admin/customize'
      preLoaderRoute: typeof AdminCustomizeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/': {
      id: '/admin/content/'
      path: '/content'
      fullPath: '/admin/content/'
      preLoaderRoute: typeof AdminContentIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/wiki/search': {
      id: '/app/wiki/search'
      path: '/wiki/search'
      fullPath: '/app/wiki/search'
      preLoaderRoute: typeof AppWikiSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/wiki/$slug': {
      id: '/app/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/app/wiki/$slug'
      preLoaderRoute: typeof AppWikiSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/schedule/confirmed': {
      id: '/app/schedule/confirmed'
      path: '/confirmed'
      fullPath: '/app/schedule/confirmed'
      preLoaderRoute: typeof AppScheduleConfirmedRouteImport
      parentRoute: typeof AppScheduleRoute
    }
    '/app/schedule/$doctorId': {
      id: '/app/schedule/$doctorId'
      path: '/$doctorId'
      fullPath: '/app/schedule/$doctorId'
      preLoaderRoute: typeof AppScheduleDoctorIdRouteImport
      parentRoute: typeof AppScheduleRoute
    }
    '/app/library/results': {
      id: '/app/library/results'
      path: '/results'
      fullPath: '/app/library/results'
      preLoaderRoute: typeof AppLibraryResultsRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/app/content/feed': {
      id: '/app/content/feed'
      path: '/feed'
      fullPath: '/app/content/feed'
      preLoaderRoute: typeof AppContentFeedRouteImport
      parentRoute: typeof AppContentRoute
    }
    '/app/content/$slug': {
      id: '/app/content/$slug'
      path: '/$slug'
      fullPath: '/app/content/$slug'
      preLoaderRoute: typeof AppContentSlugRouteImport
      parentRoute: typeof AppContentRoute
    }
    '/app/condition/$slug': {
      id: '/app/condition/$slug'
      path: '/condition/$slug'
      fullPath: '/app/condition/$slug'
      preLoaderRoute: typeof AppConditionSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/wiki/new': {
      id: '/admin/wiki/new'
      path: '/new'
      fullPath: '/admin/wiki/new'
      preLoaderRoute: typeof AdminWikiNewRouteImport
      parentRoute: typeof AdminWikiRoute
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/content/video-editor': {
      id: '/admin/content/video-editor'
      path: '/content/video-editor'
      fullPath: '/admin/content/video-editor'
      preLoaderRoute: typeof AdminContentVideoEditorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/new': {
      id: '/admin/content/new'
      path: '/content/new'
      fullPath: '/admin/content/new'
      preLoaderRoute: typeof AdminContentNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content/list': {
      id: '/admin/content/list'
      path: '/content/list'
      fullPath: '/admin/content/list'
      preLoaderRoute: typeof AdminContentListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/library/conditions/$id': {
      id: '/app/library/conditions/$id'
      path: '/conditions/$id'
      fullPath: '/app/library/conditions/$id'
      preLoaderRoute: typeof AppLibraryConditionsIdRouteImport
      parentRoute: typeof AppLibraryRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminPatientsRouteChildren {
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
}

const AdminPatientsRouteChildren: AdminPatientsRouteChildren = {
  AdminPatientsIdRoute: AdminPatientsIdRoute,
}

const AdminPatientsRouteWithChildren = AdminPatientsRoute._addFileChildren(
  AdminPatientsRouteChildren,
)

interface AdminWikiRouteChildren {
  AdminWikiNewRoute: typeof AdminWikiNewRoute
}

const AdminWikiRouteChildren: AdminWikiRouteChildren = {
  AdminWikiNewRoute: AdminWikiNewRoute,
}

const AdminWikiRouteWithChildren = AdminWikiRoute._addFileChildren(
  AdminWikiRouteChildren,
)

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCustomizeRoute: typeof AdminCustomizeRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPatientsRoute: typeof AdminPatientsRouteWithChildren
  AdminProfileRoute: typeof AdminProfileRoute
  AdminWikiRoute: typeof AdminWikiRouteWithChildren
  AdminContentListRoute: typeof AdminContentListRoute
  AdminContentNewRoute: typeof AdminContentNewRoute
  AdminContentVideoEditorRoute: typeof AdminContentVideoEditorRoute
  AdminContentIndexRoute: typeof AdminContentIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminCustomizeRoute: AdminCustomizeRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPatientsRoute: AdminPatientsRouteWithChildren,
  AdminProfileRoute: AdminProfileRoute,
  AdminWikiRoute: AdminWikiRouteWithChildren,
  AdminContentListRoute: AdminContentListRoute,
  AdminContentNewRoute: AdminContentNewRoute,
  AdminContentVideoEditorRoute: AdminContentVideoEditorRoute,
  AdminContentIndexRoute: AdminContentIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppContentRouteChildren {
  AppContentSlugRoute: typeof AppContentSlugRoute
  AppContentFeedRoute: typeof AppContentFeedRoute
}

const AppContentRouteChildren: AppContentRouteChildren = {
  AppContentSlugRoute: AppContentSlugRoute,
  AppContentFeedRoute: AppContentFeedRoute,
}

const AppContentRouteWithChildren = AppContentRoute._addFileChildren(
  AppContentRouteChildren,
)

interface AppLibraryRouteChildren {
  AppLibraryResultsRoute: typeof AppLibraryResultsRoute
  AppLibraryConditionsIdRoute: typeof AppLibraryConditionsIdRoute
}

const AppLibraryRouteChildren: AppLibraryRouteChildren = {
  AppLibraryResultsRoute: AppLibraryResultsRoute,
  AppLibraryConditionsIdRoute: AppLibraryConditionsIdRoute,
}

const AppLibraryRouteWithChildren = AppLibraryRoute._addFileChildren(
  AppLibraryRouteChildren,
)

interface AppScheduleRouteChildren {
  AppScheduleDoctorIdRoute: typeof AppScheduleDoctorIdRoute
  AppScheduleConfirmedRoute: typeof AppScheduleConfirmedRoute
}

const AppScheduleRouteChildren: AppScheduleRouteChildren = {
  AppScheduleDoctorIdRoute: AppScheduleDoctorIdRoute,
  AppScheduleConfirmedRoute: AppScheduleConfirmedRoute,
}

const AppScheduleRouteWithChildren = AppScheduleRoute._addFileChildren(
  AppScheduleRouteChildren,
)

interface AppRouteChildren {
  AppCameraRoute: typeof AppCameraRoute
  AppClinicCodeRoute: typeof AppClinicCodeRoute
  AppClinicProfileRoute: typeof AppClinicProfileRoute
  AppContentRoute: typeof AppContentRouteWithChildren
  AppEvolutionRoute: typeof AppEvolutionRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppHomeRoute: typeof AppHomeRoute
  AppLesionCameraRoute: typeof AppLesionCameraRoute
  AppLesionResultsRoute: typeof AppLesionResultsRoute
  AppLibraryRoute: typeof AppLibraryRouteWithChildren
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppScheduleRoute: typeof AppScheduleRouteWithChildren
  AppSplashRoute: typeof AppSplashRoute
  AppSupportRoute: typeof AppSupportRoute
  AppSymptomCheckerRoute: typeof AppSymptomCheckerRoute
  AppSymptomResultsRoute: typeof AppSymptomResultsRoute
  AppUvRoute: typeof AppUvRoute
  AppConditionSlugRoute: typeof AppConditionSlugRoute
  AppWikiSlugRoute: typeof AppWikiSlugRoute
  AppWikiSearchRoute: typeof AppWikiSearchRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCameraRoute: AppCameraRoute,
  AppClinicCodeRoute: AppClinicCodeRoute,
  AppClinicProfileRoute: AppClinicProfileRoute,
  AppContentRoute: AppContentRouteWithChildren,
  AppEvolutionRoute: AppEvolutionRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppHomeRoute: AppHomeRoute,
  AppLesionCameraRoute: AppLesionCameraRoute,
  AppLesionResultsRoute: AppLesionResultsRoute,
  AppLibraryRoute: AppLibraryRouteWithChildren,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppScheduleRoute: AppScheduleRouteWithChildren,
  AppSplashRoute: AppSplashRoute,
  AppSupportRoute: AppSupportRoute,
  AppSymptomCheckerRoute: AppSymptomCheckerRoute,
  AppSymptomResultsRoute: AppSymptomResultsRoute,
  AppUvRoute: AppUvRoute,
  AppConditionSlugRoute: AppConditionSlugRoute,
  AppWikiSlugRoute: AppWikiSlugRoute,
  AppWikiSearchRoute: AppWikiSearchRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterDoctorRoute: AuthRegisterDoctorRoute,
  AuthRegisterPatientRoute: AuthRegisterPatientRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
